# Generated by Django 2.2.1 on 2019-06-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190609_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Tournament'),
        ),
    ]
