# Generated by Django 2.2.1 on 2019-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_venue_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='participants_name',
            new_name='participants_name_1',
        ),
        migrations.AddField(
            model_name='team',
            name='participants_name_2',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
